update

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,14 +1,26 @@
-#!/usr/bin/env bash
-# transfer a file from our client to a server
-if [ $# -lt 3 ];
-then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
-    exit;
-fi;
+#!/bin/bash
 
-if [ $# -ge 4 ];
-then
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
+# Check if all 4 parameters are provided
+if [ "$#" -lt 4 ]; then
+    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+    exit 1
+fi
+
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key_path="$4"
+
+# Display information about the transfer
+echo "Transferring file: $file_path to $username@$server_ip:~/"
+
+# Use scp to transfer the file with strict host key checking disabled
+scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~/
+
+# Check if scp command was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transfer successful!"
 else
-    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
-fi;
+    echo "File transfer failed."
+fi
